// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3kAR7kYBBmpDW_OU9fKl3BVttq4COg3E',
    appId: '1:91157257519:web:acba162415f2f88701d5da',
    messagingSenderId: '91157257519',
    projectId: 'jogajunto-17ee0',
    authDomain: 'jogajunto-17ee0.firebaseapp.com',
    storageBucket: 'jogajunto-17ee0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_fdvglqfX9Y79FMsk4DRXbN0dB4rQy2Q',
    appId: '1:91157257519:android:226a5e6148d4372c01d5da',
    messagingSenderId: '91157257519',
    projectId: 'jogajunto-17ee0',
    storageBucket: 'jogajunto-17ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-vX1_SjOuv3HTEE_kWMr4Fz-_z2XTlik',
    appId: '1:91157257519:ios:0bb1c5aa724b5f0a01d5da',
    messagingSenderId: '91157257519',
    projectId: 'jogajunto-17ee0',
    storageBucket: 'jogajunto-17ee0.appspot.com',
    iosBundleId: 'com.example.jogaJunto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-vX1_SjOuv3HTEE_kWMr4Fz-_z2XTlik',
    appId: '1:91157257519:ios:0dbd2c92109f6bff01d5da',
    messagingSenderId: '91157257519',
    projectId: 'jogajunto-17ee0',
    storageBucket: 'jogajunto-17ee0.appspot.com',
    iosBundleId: 'com.example.jogaJunto.RunnerTests',
  );
}
